# -*- coding: utf-8 -*-
"""Bootcamp_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fULWQxZP1rXrxGSDboNWy3R8DQiz57HE
"""

import random

def get_computer_choice():
    choices = ["rock", "paper", "scissors"]
    return random.choice(choices)

def determine_winner(player_choice, computer_choice):
    if player_choice == computer_choice:
        return "It's a tie!"
    elif (player_choice == "rock" and computer_choice == "scissors") or \
         (player_choice == "paper" and computer_choice == "rock") or \
         (player_choice == "scissors" and computer_choice == "paper"):
        return "Player wins!"
    else:
        return "Computer wins!"

def get_valid_player_choice():
    valid_choices = ["rock", "paper", "scissors"]
    while True:
        player_choice = input("Please choose rock, paper, scissors or exit: ").lower()
        if player_choice in valid_choices:
            return player_choice
        elif player_choice == "exit":
            print("Exiting the game. Hope you had fun! Come back for more rock-paper-scissors action!")
            return None
        else:
            print("Invalid choice. Please enter 'rock', 'paper', or 'scissors'. Try again!")

def play_round():
    player_choice = get_valid_player_choice()
    if player_choice is None:
        return None, None

    computer_choice = get_computer_choice()
    print(f"Computer chose: {computer_choice}")
    result = determine_winner(player_choice, computer_choice)
    print()
    print(result)
    print()  # Adding a blank line for better readability
    return result, player_choice

def ask_play_again():
    while True:
        response = input("Do you want to play another game? (yes/no): ").lower()
        if response in ["yes", "no"]:
            return response
        else:
            print("Invalid response. Please enter 'yes' or 'no'.")

def game_intro():
    print("🎉 Welcome to the Ultimate Rock, Paper, Scissors Showdown! 🎉")
    print("Here's how it works:")
    print("🪨 Rock crushes Scissors - Time to unleash the boulder!")
    print("✂️ Scissors cuts Paper - Sharp enough to make a cut!")
    print("📜 Paper covers Rock - A smooth cover for the mighty rock!")
    print("🌟 Your goal: Win 2 out of 3 rounds to be crowned the champion! 🌟")
    print("🚪 Type 'exit' at any time to gracefully bow out of the arena.")
    print("Let's get ready to rumble! 💥")
    print("*" * 50)
# While I was using colab for emojis, I tried to make my game a little more enjoyable by using Windows's emoji panel.
def tas_kagit_makas_VİLDAN_BOZKURT():
    total_games = 0
    total_rounds = 0

    game_intro()

    while True:
        player_wins = 0
        computer_wins = 0

        while player_wins < 2 and computer_wins < 2:
            total_games += 1
            player_round_wins = 0
            computer_round_wins = 0

            while player_round_wins < 2 and computer_round_wins < 2:
                total_rounds += 1
                result, player_choice = play_round()
                if result is None:
                    return

                if "Player wins!" in result:
                    player_round_wins += 1
                    player_wins += 1
                    print("Well done! You're a rock-paper-scissors champion this round! 🏆")
                elif "Computer wins!" in result:
                    computer_round_wins += 1
                    computer_wins += 1
                    print("Oh no! The computer is victorious this round. It’s plotting world domination!")
                else:
                    print("A tie! Looks like you and the computer are in sync!")

                print(f"Round Score -> Player: {player_round_wins}, Computer: {computer_round_wins}")
                print("*" * 50)

            print(f"Game Score -> Player: {player_wins}, Computer: {computer_wins}")
            print("*" * 50)

        if player_wins == 2:
            print("Congratulations! You won the game! You've beaten the computer at its own game! 🎉🏆")
        elif computer_wins == 2:
            print("Computer wins the game! Better luck next time. It looks like it had a few tricks up its sleeve!")

        print(f"Total Games Played: {total_games}")
        print(f"Total Rounds Played: {total_rounds}")
        print(f"Total Player Wins: {player_wins}")
        print(f"Total Computer Wins: {computer_wins}")
        print("Thanks for playing! Remember, every game is a chance to improve your strategy.")

        # Ask if the player wants to play again
        player_response = ask_play_again()
        computer_response = random.choice(["yes", "no"])
        print(f"The computer's response: {'yes' if computer_response == 'yes' else 'no'}")

        if player_response == "no":
            if computer_response == "no":
                print("The computer has decided not to play again. Goodbye!")
                break
            else:
                print("Looks like the computer is still up for a game! Let's start a new round.")
                continue
        else:
            if computer_response == "no":
                print("The computer has decided not to play again. Goodbye!")
                break

# To start the game
tas_kagit_makas_VİLDAN_BOZKURT()